import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Weather App
        </h1>
      </main>

      <footer className={styles.footer}>
        Copyright &copy; <span className='text-info' style={{fontWeight : '700'}}>Weather App</span>
      </footer>
    </div>
  )
}

export default Home